<?php
declare(strict_types=1);
if (!empty($GLOBALS['app_subcategory_modal_rendered'])) return;
$GLOBALS['app_subcategory_modal_rendered'] = true;
?>
<form id="appSubcategoryForm" class="app-modal-form hidden" data-component="subcategory-form" novalidate>
    <input type="hidden" name="id" value="">
    <div class="modal-header">
        <div class="modal-header-copy"><h2 data-subcategory-form-title>Add Subcategory</h2><p>Create or update a category-based product subcategory.</p></div>
        <button class="modal-close" type="button" data-modal-close aria-label="Close Subcategory form" title="Close"><i data-lucide="x"></i></button>
    </div>
    <div class="modal-body"><div class="form-grid">
        <div class="field"><label for="appSubcategoryCode">Subcategory Code</label><input id="appSubcategoryCode" name="subcategory_code" maxlength="30" readonly aria-readonly="true" placeholder="Auto generated"></div>
        <div class="field two-span"><label for="appSubcategoryCategory" class="required">Category</label><select id="appSubcategoryCategory" name="category_id" required data-placeholder="Select category" data-required-message="Please select a category."><option value="">Select category</option></select></div>
        <div class="field full"><label for="appSubcategoryName" class="required">Subcategory Name</label><input id="appSubcategoryName" name="subcategory_name" maxlength="120" required placeholder="Enter subcategory name" data-required-message="Subcategory name is required."></div>
    </div></div>
    <div class="modal-footer"><div class="buttons"><button class="btn gray" type="button" data-modal-close>Cancel</button><button class="btn btn-primary" type="submit" data-subcategory-save>Save Subcategory</button></div></div>
</form>
<script>
(function(window,document){"use strict";
var form=null,titleNode=null,saveButton=null,categorySelect=null,activeOptions=null,initialized=false;
function ensure(){if(initialized)return Boolean(form);form=document.querySelector('[data-component="subcategory-form"]');if(!form)return false;titleNode=form.querySelector('[data-subcategory-form-title]');saveButton=form.querySelector('[data-subcategory-save]');if(window.GlobalSelect)categorySelect=GlobalSelect.init('#appSubcategoryCategory',{placeholder:'Select or type category'});form.addEventListener('submit',submit);initialized=true;return true;}
function setCategories(rows,selected){var items=(rows||[]).map(function(row){return{value:row.id,text:(row.category_code?row.category_code+' - ':'')+row.category_name};});if(categorySelect&&typeof categorySelect.setOptions==='function')categorySelect.setOptions(items,selected||'');else{form.category_id.innerHTML='<option value="">Select category</option>';items.forEach(function(item){var o=document.createElement('option');o.value=item.value;o.textContent=item.text;form.category_id.appendChild(o);});form.category_id.value=selected||'';}}
function reset(){if(!ensure())return;form.reset();form.id.value="";form.subcategory_code.value="";if(categorySelect&&categorySelect.setValue)categorySelect.setValue('');if(window.Validation)Validation.clearForm(form);}
function fill(row){reset();form.id.value=row&&row.id?String(row.id):"";form.subcategory_code.value=row&&row.subcategory_code?String(row.subcategory_code):"";form.subcategory_name.value=row&&row.subcategory_name?String(row.subcategory_name):"";}
function openModal(options){if(!window.AppModal){if(window.App)App.showError(null,'Common modal component is unavailable.');return false;}titleNode.textContent=options.title||(options.mode==='edit'?'Edit Subcategory':'Add Subcategory');saveButton.textContent=options.mode==='edit'?'Update Subcategory':'Save Subcategory';AppModal.open(form,{size:options.size||'lg',focusSelector:'[name="category_id"]',onClose:function(reason){if(window.Validation)Validation.clearForm(form);var x=activeOptions;activeOptions=null;if(x&&typeof x.onClosed==='function')x.onClosed(reason||'close');}});if(window.lucide)window.lucide.createIcons();return true;}
async function open(options){options=options||{};if(!ensure())return false;activeOptions=options;var mode=String(options.mode||(options.id?'edit':'create')).toLowerCase();options.mode=mode;var apiUrl=options.apiUrl||'api/subcategory.php';try{var optionsResult=await App.api(apiUrl+'?options=1');var selectedCategory=options.categoryId?String(options.categoryId):'';if(mode==='edit'){var id=Number(options.id||0);if(!id){App.showError(null,'Subcategory record ID is required.');activeOptions=null;return false;}var result=await App.api(apiUrl+'?id='+id);var row=result.data.subcategory||{};fill(row);selectedCategory=String(row.category_id||'');form.subcategory_code.value=row.subcategory_code||'';}else{reset();form.subcategory_code.value=optionsResult.data.next_subcategory_code||'';}setCategories(optionsResult.data.categories||[],selectedCategory);}catch(error){activeOptions=null;App.showError(error,'Unable to load Subcategory form.');return false;}return openModal(options);}
async function submit(event){event.preventDefault();if(window.Validation){Validation.clearForm(form);if(!Validation.validateForm(form))return;}var id=Number(form.id.value||0);var body={id:id||undefined,category_id:Number(form.category_id.value||0),subcategory_name:form.subcategory_name.value.trim()};saveButton.disabled=true;try{var result=await App.api((activeOptions&&activeOptions.apiUrl)||'api/subcategory.php',{method:id?'PUT':'POST',body:body});var row=result.data&&result.data.subcategory?result.data.subcategory:null;if(window.showToast)showToast(result.message||'Subcategory saved successfully.',{type:'success',duration:2});var callback=activeOptions&&typeof activeOptions.onSaved==='function'?activeOptions.onSaved:null;window.dispatchEvent(new CustomEvent('app:subcategory-saved',{detail:{subcategory:row,mode:id?'edit':'create'}}));if(!activeOptions||activeOptions.closeOnSaved!==false){if(window.AppModal&&AppModal.isOpen())AppModal.close('saved');}if(callback)callback(row,result);}catch(error){var applied=false;if(window.Validation&&error&&error.errors&&Object.keys(error.errors).length)applied=Validation.applyErrors(form,error.errors);if(!applied)App.showError(error,'Unable to save Subcategory record.');}finally{saveButton.disabled=false;}}
window.AppSubcategoryForm={open:open,openCreate:function(o){o=o||{};o.mode='create';return open(o);},openEdit:function(id,o){o=o||{};o.mode='edit';o.id=id;return open(o);},close:function(){return window.AppModal&&AppModal.isOpen()?AppModal.close('programmatic'):false;},reset:reset,getForm:function(){ensure();return form;}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})(window,document);
</script>
