<?php
require_once __DIR__ . '/include/web-config.php';
$pageTitle='Customer Order';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="<?php echo web_h(app_theme_color()); ?>"><title><?php echo web_h($pageTitle); ?> · <?php echo web_h(app_name()); ?></title><?php render_frontend_config_script(); ?><script src="assets/js/runtime.js"></script><link rel="stylesheet" href="assets/css/core.css"><link rel="stylesheet" href="assets/css/components.css"><link rel="stylesheet" href="assets/css/theme.css"><script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js" defer></script></head>
<body><div class="app-shell"><?php require __DIR__.'/include/sidebar.php'; ?><main class="main-stage"><?php require __DIR__.'/include/topbar.php'; ?><section class="page-content"><script src="assets/js/toaster.js"></script><script src="assets/js/app.js"></script><script src="assets/js/theme.js"></script><script src="assets/js/layout.js"></script><script src="assets/js/validation.js"></script><script src="assets/js/global-select.js"></script><script src="assets/js/aqua-tax-mode.js"></script>
<div class="page-heading"><div><h1 id="heading">Customer Order</h1><p>Order confirmation does not reduce stock. Delivery status updates only from actual customer delivery.</p></div><div class="heading-actions"><span class="pill pending" id="taxBadge" hidden>NON GST</span><a class="btn gray" href="order-list.php"><i data-lucide="list"></i>Order List</a></div></div>
<form id="orderForm" novalidate><div class="card form-section"><div class="card-header"><h2 class="section-heading"><i data-lucide="clipboard-list"></i>Order Details</h2></div><div class="card-body"><div class="form-row">
<div class="field col-3"><label>Order No</label><input class="input" id="orderNo" type="text" readonly placeholder="Auto generated"></div><div class="field col-3"><label class="required" for="orderDate">Order Date</label><input class="input" id="orderDate" type="date" value="<?php echo web_h(date('Y-m-d')); ?>"></div><div class="field col-6"><label class="required" for="customerId">Customer</label><select class="select" id="customerId"><option value="">Select Customer</option></select></div>
</div><div class="form-row"><div class="field col-4"><label>Delivery Status</label><input class="input" id="deliveryStatus" type="text" readonly value="Pending"></div><div class="field col-8"><label for="remarks">Remarks</label><input class="input" id="remarks" type="text" maxlength="255" placeholder="Optional"></div></div></div></div>
<div class="app-section-title">Order Product Entry</div><div class="card form-section"><div class="card-body"><div class="form-row">
<div class="field col-4"><label for="entryProduct">Product</label><select class="select" id="entryProduct"><option value="">Select Product</option></select></div><div class="field col-2"><label id="primaryQtyLabel">Primary Qty</label><input class="input" id="primaryQty" type="text" inputmode="decimal" placeholder="0.000"></div><div class="field col-2"><label id="secondaryQtyLabel">Secondary Qty</label><input class="input" id="secondaryQty" type="text" inputmode="decimal" placeholder="0.000" disabled></div><div class="field col-2"><label>Primary Rate</label><input class="input" id="primaryRate" type="text" inputmode="decimal" placeholder="0.00"></div><div class="field col-1 discount-field"><label>Disc</label><input class="input" id="discountValue" type="text" inputmode="decimal" placeholder="0.00"></div><div class="field col-1"><label>&nbsp;</label><button class="btn btn-primary" id="addItem" type="button"><i data-lucide="plus"></i>Add</button></div>
</div></div></div>
<div class="card table-card form-section"><div class="app-table-wrap"><table class="app-editable-table"><thead><tr><th>#</th><th>Product</th><th>Primary Qty</th><th>Secondary Qty</th><th>Rate</th><th class="discount-column">Discount %</th><th>Delivered</th><th>Pending</th><th>Amount</th><th></th></tr></thead><tbody id="itemsBody"><tr><td class="empty" colspan="10">No Products added.</td></tr></tbody></table></div></div>
<div class="app-entry-grid"><div class="card form-section"><div class="card-header"><h2 class="section-heading"><i data-lucide="calculator"></i>Order Summary</h2></div><div class="card-body"><div class="app-total-group"><div class="app-total-line"><span>Gross</span><strong id="sumGross">₹0.00</strong></div><div class="app-total-line discount-field"><span>Overall Discount</span><span><select class="select" id="overallDiscountType"><option value="1">None</option><option value="2">Percentage</option><option value="3">Amount</option></select><input class="input" id="overallDiscountValue" type="text" inputmode="decimal" placeholder="0.00"></span></div><div class="app-total-line tax-line"><span>Tax</span><strong id="sumTax">₹0.00</strong></div><div class="app-total-line"><span>Other Charges</span><input class="input" id="otherCharges" type="text" inputmode="decimal" placeholder="0.00"></div><div class="app-total-line"><span>Round Off</span><span><strong id="sumRound">₹0.00</strong> <button class="btn gray" id="roundButton" type="button">Round Off</button></span></div><div class="app-total-line"><span>Grand Total</span><strong id="sumGrand">₹0.00</strong></div></div></div></div></div>
<div class="app-summary-actions"><button class="btn gray" id="draftButton" type="button"><i data-lucide="save"></i>Save Draft</button><button class="btn btn-primary" id="confirmButton" type="button"><i data-lucide="check-circle-2"></i>Confirm Order</button></div></form>
<script>
(function(window,document){"use strict";var params=new URLSearchParams(location.search),reference=params.get("ref")||"";var customerSelect=GlobalSelect.init("#customerId",{placeholder:"Select Customer"}),productSelect=GlobalSelect.init("#entryProduct",{placeholder:"Select Product"});var state={actions:[],customers:[],products:[],map:{},items:[],taxMode:AquaTaxMode.get(),round:0,locked:false};var A_CREATE=2,A_UPDATE=3,A_DRAFT=10,A_POST=11,A_DISC=35,A_TAX=49;
function n(v){v=Number(v||0);return Number.isFinite(v)?v:0}function r(v,p){var m=Math.pow(10,p||2);return Math.round((n(v)+Number.EPSILON)*m)/m}function money(v){return"₹"+n(v).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function has(x){return state.actions.map(Number).indexOf(Number(x))!==-1}function unit(u){return u?(u.short_name||u.unit_name||"Unit"):"Unit"}
function setTax(m){state.taxMode=Number(m)===0?0:1;document.getElementById("taxBadge").hidden=state.taxMode!==0;document.querySelectorAll(".tax-line").forEach(function(x){x.hidden=state.taxMode===0});recalc()}document.addEventListener("keydown",function(e){if(e.ctrlKey&&e.shiftKey&&String(e.key).toLowerCase()==="u"&&!state.locked&&has(A_TAX)){e.preventDefault();setTax(AquaTaxMode.toggle())}});
function options(data,selected){state.customers=data.customers||[];state.products=data.products||[];state.map={};state.products.forEach(function(p){state.map[String(p.id)]=p});customerSelect.setOptions(state.customers.map(function(c){return{value:String(c.id),text:(c.customer_code?c.customer_code+" - ":"")+c.customer_name}}),selected||"");productSelect.setOptions(state.products.map(function(p){return{value:String(p.id),text:(p.product_code?p.product_code+" - ":"")+p.product_name}}),"")}
async function reloadProducts(){var cid=Number(document.getElementById("customerId").value||0);if(!cid)return;try{var x=await App.api("api/orders.php?options=1&customer_id="+cid);options(x.data,String(cid))}catch(e){App.showError(e,"Unable to load Customer pricing.")}}
function current(){return state.map[String(document.getElementById("entryProduct").value||"")]||null}function refresh(){var p=current(),s=document.getElementById("secondaryQty");if(!p){document.getElementById("primaryQtyLabel").textContent="Primary Qty";document.getElementById("secondaryQtyLabel").textContent="Secondary Qty";s.disabled=true;document.getElementById("primaryRate").value="";return}document.getElementById("primaryQtyLabel").textContent=unit(p.primary_unit)+" Qty";document.getElementById("secondaryQtyLabel").textContent=p.secondary_unit?unit(p.secondary_unit)+" Qty":"Secondary Qty";s.disabled=!p.secondary_unit;if(!p.secondary_unit)s.value="";document.getElementById("primaryRate").value=n(p.primary_price)>0?n(p.primary_price).toFixed(2):""}
function add(){var p=current();if(!p){showToast("Select Product.",{type:"warning",duration:2});return}if(state.items.some(function(x){return Number(x.product_id)===Number(p.id)})){showToast("Product already added.",{type:"warning",duration:2});return}var pq=n(document.getElementById("primaryQty").value),sq=p.secondary_unit?n(document.getElementById("secondaryQty").value):0;if(pq<=0&&sq<=0){showToast("Enter quantity.",{type:"warning",duration:2});return}state.items.push({item_id:0,product_id:Number(p.id),primary_qty:r(pq,3),secondary_qty:r(sq,3),primary_rate:r(document.getElementById("primaryRate").value,2),discount_type:n(document.getElementById("discountValue").value)>0?2:1,discount_value:r(document.getElementById("discountValue").value,2),delivered_base_qty:0,snapshot:p});productSelect.setValue("");document.getElementById("entryProduct").value="";["primaryQty","secondaryQty","primaryRate","discountValue"].forEach(function(id){document.getElementById(id).value=""});refresh();render()}
function calc(x){var p=state.map[String(x.product_id)]||x.snapshot||{},sc=p.secondary_unit?Math.max(1,n(p.secondary_unit.conversion_qty)):0,g=r(n(x.primary_qty)*n(x.primary_rate)+n(x.secondary_qty)*(n(x.primary_rate)*sc),2),d=Number(x.discount_type)===2?r(g*Math.min(100,n(x.discount_value))/100,2):(Number(x.discount_type)===3?Math.min(g,n(x.discount_value)):0),base=n(x.primary_qty)*Math.max(1,n(p.primary_unit&&p.primary_unit.conversion_qty||1))+n(x.secondary_qty)*sc;return{gross:g,disc:d,after:Math.max(0,r(g-d,2)),base:r(base,3)}}
function render(){var b=document.getElementById("itemsBody");if(!state.items.length){b.innerHTML='<tr><td class="empty" colspan="10">No Products added.</td></tr>';recalc();return}b.innerHTML=state.items.map(function(x,i){var p=state.map[String(x.product_id)]||x.snapshot||{},c=calc(x),del=n(x.delivered_base_qty),pend=Math.max(0,c.base-del);return'<tr data-index="'+i+'"><td>'+(i+1)+'</td><td><strong>'+esc(p.product_name||"-")+'</strong></td><td><input class="input pq" type="text" inputmode="decimal" value="'+(n(x.primary_qty)||"")+'"><div class="muted">'+esc(unit(p.primary_unit))+'</div></td><td>'+(p.secondary_unit?'<input class="input sq" type="text" inputmode="decimal" value="'+(n(x.secondary_qty)||"")+'"><div class="muted">'+esc(unit(p.secondary_unit))+'</div>':'—')+'</td><td><input class="input rate" type="text" inputmode="decimal" value="'+n(x.primary_rate).toFixed(2)+'"></td><td class="discount-column">'+(has(A_DISC)?'<input class="input disc" type="text" inputmode="decimal" value="'+(n(x.discount_value)||"")+'">':'—')+'</td><td>'+del.toFixed(3)+'</td><td>'+pend.toFixed(3)+'</td><td><strong>'+money(c.after)+'</strong></td><td><button class="action-button remove" type="button" '+(del>0?'disabled':'')+'><i data-lucide="trash-2"></i></button></td></tr>'}).join("");if(window.lucide)lucide.createIcons();recalc()}
function read(){document.querySelectorAll("#itemsBody tr[data-index]").forEach(function(row){var x=state.items[Number(row.dataset.index)],p=state.map[String(x.product_id)]||x.snapshot||{};x.primary_qty=r(row.querySelector(".pq").value,3);var sq=row.querySelector(".sq");x.secondary_qty=sq?r(sq.value,3):0;x.primary_rate=r(row.querySelector(".rate").value,2);var d=row.querySelector(".disc");if(d){x.discount_value=r(d.value,2);x.discount_type=x.discount_value>0?2:1}})}
function recalc(){read();var gross=0,base=0;state.items.forEach(function(x){var c=calc(x);gross+=c.gross;base+=c.after});var ot=Number(document.getElementById("overallDiscountType").value||1),ov=n(document.getElementById("overallDiscountValue").value),overall=ot===2?r(base*Math.min(100,ov)/100,2):(ot===3?Math.min(base,ov):0),tax=0,net=0;state.items.forEach(function(x){var p=state.map[String(x.product_id)]||x.snapshot||{},c=calc(x),amt=Math.max(0,c.after-(base>0?overall*c.after/base:0)),pct=state.taxMode===1?n(p.tax_percentage):0;if(pct>0){if(Number(p.gst_type)===1){var taxable=amt*100/(100+pct);tax+=amt-taxable;net+=amt}else{var t=amt*pct/100;tax+=t;net+=amt+t}}else net+=amt});var before=r(net+n(document.getElementById("otherCharges").value),2),ro=state.round?r(Math.round(before)-before,2):0,grand=r(before+ro,2);document.getElementById("sumGross").textContent=money(gross);document.getElementById("sumTax").textContent=money(tax);document.getElementById("sumRound").textContent=money(ro);document.getElementById("sumGrand").textContent=money(grand);document.getElementById("roundButton").textContent=state.round?"Unround":"Round Off"}
function payload(intent){read();return{ref:reference||undefined,intent:intent,sale_date:document.getElementById("orderDate").value,customer_id:Number(document.getElementById("customerId").value||0),tax_mode:state.taxMode,items_json:JSON.stringify(state.items),overall_discount_type:Number(document.getElementById("overallDiscountType").value||1),overall_discount_value:n(document.getElementById("overallDiscountValue").value),other_charges:n(document.getElementById("otherCharges").value),round_off_enabled:state.round,remarks:document.getElementById("remarks").value.trim()}}
async function save(intent){if(!state.items.length){showToast("Add at least one Product.",{type:"warning",duration:2});return}try{var x=await App.api("api/orders.php",{method:"POST",body:payload(intent)});showToast(x.message||"Saved.",{type:"success",duration:2});setTimeout(function(){location.href="order-list.php"},600)}catch(e){App.showError(e,"Unable to save Customer Order.")}}
function statusText(v){return Number(v)===3?"Delivered":(Number(v)===2?"Partially Delivered":(Number(v)===4?"Cancelled":"Pending"))}
function fill(data){var o=data.order||{};state.taxMode=Number(o.tax_mode)===0?0:1;state.round=Number(o.round_off_enabled||0);state.locked=Number(o.delivery_status)===3||Number(o.delivery_status)===4||Number(o.status)===3;document.getElementById("orderNo").value=o.sale_no||"";document.getElementById("orderDate").value=o.sale_date||"";document.getElementById("remarks").value=o.remarks||"";document.getElementById("deliveryStatus").value=statusText(o.delivery_status);document.getElementById("overallDiscountType").value=String(Number(o.overall_discount_type||1));document.getElementById("overallDiscountValue").value=n(o.overall_discount_value)>0?n(o.overall_discount_value).toFixed(2):"";document.getElementById("otherCharges").value=n(o.other_charges)>0?n(o.other_charges).toFixed(2):"";customerSelect.setValue(String(o.customer_id));document.getElementById("customerId").value=String(o.customer_id);state.items=(data.items||[]).map(function(x){return{item_id:Number(x.id),product_id:Number(x.product_id),primary_qty:n(x.primary_qty),secondary_qty:n(x.secondary_qty),primary_rate:n(x.rate),discount_type:Number(x.discount_type||1),discount_value:n(x.discount_value),delivered_base_qty:n(x.delivered_base_qty),snapshot:state.map[String(x.product_id)]||{product_name:x.product_name,gst_type:x.gst_type,primary_unit:{unit_name:x.primary_unit_name,short_name:x.primary_short_name,conversion_qty:x.conversion_qty},secondary_unit:x.secondary_product_unit_id?{unit_name:x.secondary_unit_name,short_name:x.secondary_short_name,conversion_qty:x.secondary_conversion_qty}:null,tax_percentage:x.tax_percentage}}});setTax(state.taxMode);render();if(state.locked)lock()}
function lock(){document.querySelectorAll("#orderForm input,#orderForm select,#orderForm button").forEach(function(el){el.disabled=true});document.getElementById("draftButton").hidden=true;document.getElementById("confirmButton").hidden=true}
async function load(){try{var o=await App.api("api/orders.php?options=1");state.actions=(o.data.allowed_actions||[]).map(Number);options(o.data,"");if(!has(A_TAX)&&!reference)state.taxMode=1;document.querySelectorAll(".discount-field,.discount-column").forEach(function(x){x.hidden=!has(A_DISC)});document.getElementById("draftButton").hidden=!has(A_DRAFT);document.getElementById("confirmButton").hidden=!has(A_POST);if(reference){var x=await App.api("api/orders.php?ref="+encodeURIComponent(reference));state.actions=(x.data.allowed_actions||[]).map(Number);var cid=Number(x.data.order.customer_id||0);var p=await App.api("api/orders.php?options=1&customer_id="+cid);options(p.data,String(cid));fill(x.data)}else{setTax(state.taxMode);if(!has(A_CREATE))lock()}}catch(e){App.showError(e,"Unable to load Customer Order.");lock()}if(window.lucide)lucide.createIcons()}
document.getElementById("customerId").addEventListener("change",reloadProducts);document.getElementById("entryProduct").addEventListener("change",refresh);document.getElementById("addItem").addEventListener("click",add);document.getElementById("itemsBody").addEventListener("input",recalc);document.getElementById("itemsBody").addEventListener("click",function(e){var b=e.target.closest(".remove");if(!b||b.disabled)return;state.items.splice(Number(b.closest("tr").dataset.index),1);render()});["overallDiscountType","overallDiscountValue","otherCharges"].forEach(function(id){document.getElementById(id).addEventListener("input",recalc);document.getElementById(id).addEventListener("change",recalc)});document.getElementById("roundButton").addEventListener("click",function(){state.round=state.round?0:1;recalc()});document.getElementById("draftButton").addEventListener("click",function(){save("draft")});document.getElementById("confirmButton").addEventListener("click",function(){save("confirm")});load();
})(window,document);
</script></section><?php require __DIR__.'/include/footer.php'; ?></main></div></body></html>
