<?php
require_once __DIR__ . '/include/web-config.php';
$pageTitle = 'Truck Return';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="<?php echo web_h(app_theme_color()); ?>"><title><?php echo web_h($pageTitle); ?> · <?php echo web_h(app_name()); ?></title><?php render_frontend_config_script(); ?><script src="assets/js/runtime.js"></script><link rel="stylesheet" href="assets/css/core.css"><link rel="stylesheet" href="assets/css/components.css"><link rel="stylesheet" href="assets/css/theme.css"><script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js" defer></script></head>
<body><div class="app-shell"><?php require __DIR__.'/include/sidebar.php'; ?><main class="main-stage"><?php require __DIR__.'/include/topbar.php'; ?><section class="page-content"><script src="assets/js/toaster.js"></script><script src="assets/js/app.js"></script><script src="assets/js/theme.js"></script><script src="assets/js/layout.js"></script><script src="assets/js/validation.js"></script>
<div class="page-heading"><div><h1>Truck Return / Closing</h1><p>Return remaining filled stock, collected empty cans and damaged cans to Plant, then close the trip.</p></div><div class="heading-actions"><a class="btn gray" href="line-supply-list.php"><i data-lucide="list"></i>Line Supply List</a><a class="btn gray" id="deliveryLink" href="#"><i data-lucide="package-check"></i>Customer Delivery</a></div></div>

<div class="card form-section"><div class="card-header"><h2 class="section-heading"><i data-lucide="truck"></i>Trip Details</h2></div><div class="card-body"><div class="form-row"><div class="field col-2"><label>Supply No</label><input class="input" id="supplyNo" type="text" readonly></div><div class="field col-2"><label>Date</label><input class="input" id="supplyDate" type="date" readonly></div><div class="field col-3"><label>Truck</label><input class="input" id="truck" type="text" readonly></div><div class="field col-2"><label>Line</label><input class="input" id="line" type="text" readonly></div><div class="field col-2"><label>Line Man</label><input class="input" id="lineMan" type="text" readonly></div><div class="field col-1"><label>Status</label><input class="input" id="tripStatus" type="text" readonly></div></div></div></div>

<div class="app-section-title">Stock Return</div>
<div class="card table-card form-section"><div class="app-table-wrap"><table class="app-editable-table"><thead><tr><th>#</th><th>Product</th><th>Loaded</th><th>Sold</th><th>Expected Filled Return</th><th>Actual Filled Return</th><th>Filled Short</th><th>Empty Collected</th><th>Actual Empty Return</th><th>Empty Short</th><th>Damaged Collected</th><th>Actual Damaged Return</th><th>Damaged Short</th><th>Reason</th></tr></thead><tbody id="returnBody"><tr><td class="empty" colspan="14">Loading Truck Return...</td></tr></tbody></table></div></div>

<div class="app-split-grid"><div class="card form-section"><div class="card-header"><h2 class="section-heading"><i data-lucide="indian-rupee"></i>Trip Financial Summary</h2></div><div class="card-body"><div class="app-total-group"><div class="app-total-line"><span>Invoice Count</span><strong id="invoiceCount">0</strong></div><div class="app-total-line"><span>Total Sales</span><strong id="totalSales">₹0.00</strong></div><div class="app-total-line"><span>Cash Collected</span><strong id="cash">₹0.00</strong></div><div class="app-total-line"><span>UPI Collected</span><strong id="upi">₹0.00</strong></div><div class="app-total-line"><span>Bank Collected</span><strong id="bank">₹0.00</strong></div><div class="app-total-line"><span>Cheque Collected</span><strong id="cheque">₹0.00</strong></div><div class="app-total-line"><span>Total Received</span><strong id="totalReceived">₹0.00</strong></div><div class="app-total-line"><span>Outstanding</span><strong id="outstanding">₹0.00</strong></div></div></div></div><div class="card form-section"><div class="card-header"><h2 class="section-heading"><i data-lucide="clipboard-check"></i>Return Confirmation</h2></div><div class="card-body"><div class="field"><label>Return Remarks</label><textarea class="input" id="returnRemarks" rows="4" maxlength="255" placeholder="Optional return remarks"></textarea></div><p class="muted">Any filled / empty / damaged shortage requires a reason against that Product.</p></div></div></div>

<div class="app-summary-actions"><button class="btn btn-primary" id="returnButton" type="button" hidden><i data-lucide="undo-2"></i>Submit Truck Return</button><button class="btn btn-primary" id="closeButton" type="button" hidden><i data-lucide="lock-keyhole"></i>Close Trip</button></div>

<script>
(function(window,document){"use strict";
var params=new URLSearchParams(window.location.search),ref=params.get("ref")||"";
var ACTION_FINALIZE=12,ACTION_RETURN=32;
var state={actions:[],trip:null,items:[],financial:{}};
function n(v){v=Number(v||0);return Number.isFinite(v)?v:0}
function r(v,p){var m=Math.pow(10,p||3);return Math.round((n(v)+Number.EPSILON)*m)/m}
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function money(v){return "₹"+n(v).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function has(a){return state.actions.map(Number).indexOf(Number(a))!==-1}
function statusLabel(s){return({1:"Draft",2:"Loaded",3:"In Route",4:"Returned",5:"Closed",6:"Cancelled"})[Number(s)]||"Unknown"}
function isReusable(x){return Number(x.container_type)===1}
function returnEditable(){return state.trip&&[2,3].indexOf(Number(state.trip.status))!==-1&&has(ACTION_RETURN)}
function rowActual(item,key,fallback){if(Number(state.trip.status)>=4)return n(item[key]);return n(fallback)}
function rowData(item){var expected=n(item.expected_return_qty),empty=n(item.empty_collected_qty),damaged=n(item.damaged_collected_qty);return{product_id:Number(item.product_id),actual_return_qty:rowActual(item,"returned_base_qty",expected),actual_empty_return_qty:isReusable(item)?rowActual(item,"empty_returned_to_plant_qty",empty):0,actual_damaged_return_qty:isReusable(item)?rowActual(item,"damaged_returned_to_plant_qty",damaged):0,reason:item.return_reason||""}}
function renderHeader(){var t=state.trip||{};document.getElementById("supplyNo").value=t.supply_no||"";document.getElementById("supplyDate").value=t.supply_date||"";document.getElementById("truck").value=(t.vehicle_no||"")+(t.vehicle_name?" - "+t.vehicle_name:"");document.getElementById("line").value=(t.line_code?t.line_code+" - ":"")+(t.line_name||"");document.getElementById("lineMan").value=(t.employee_code?t.employee_code+" - ":"")+(t.line_man_name||"");document.getElementById("tripStatus").value=statusLabel(t.status);document.getElementById("returnRemarks").value=t.return_remarks||"";document.getElementById("deliveryLink").href="line-sale-form.php?ref="+encodeURIComponent(ref)}
function renderItems(){var body=document.getElementById("returnBody"),editable=returnEditable();if(!state.items.length){body.innerHTML='<tr><td class="empty" colspan="14">No Truck Loading Products found.</td></tr>';return}body.innerHTML=state.items.map(function(item,index){var d=rowData(item),loaded=n(item.loaded_base_qty),expected=n(item.expected_return_qty),sold=Math.max(0,r(loaded-expected,3)),filledShort=Math.max(0,r(expected-d.actual_return_qty,3)),empty=n(item.empty_collected_qty),emptyShort=Math.max(0,r(empty-d.actual_empty_return_qty,3)),damaged=n(item.damaged_collected_qty),damagedShort=Math.max(0,r(damaged-d.actual_damaged_return_qty,3)),reusable=isReusable(item),lock=editable?"":" readonly";return '<tr data-index="'+index+'"><td>'+(index+1)+'</td><td><strong>'+esc(item.product_name||"-")+'</strong><div class="muted">'+esc(item.product_code||"")+'</div></td><td>'+loaded.toFixed(3)+'</td><td>'+sold.toFixed(3)+'</td><td>'+expected.toFixed(3)+'</td><td><input class="input actual-filled" type="text" inputmode="decimal" value="'+(d.actual_return_qty?d.actual_return_qty.toFixed(3):"")+'"'+lock+'></td><td><strong class="filled-short">'+filledShort.toFixed(3)+'</strong></td><td>'+(reusable?empty.toFixed(3):'—')+'</td><td>'+(reusable?'<input class="input actual-empty" type="text" inputmode="decimal" value="'+(d.actual_empty_return_qty?d.actual_empty_return_qty.toFixed(3):"")+'"'+lock+'>':'—')+'</td><td><strong class="empty-short">'+(reusable?emptyShort.toFixed(3):'—')+'</strong></td><td>'+(reusable?damaged.toFixed(3):'—')+'</td><td>'+(reusable?'<input class="input actual-damaged" type="text" inputmode="decimal" value="'+(d.actual_damaged_return_qty?d.actual_damaged_return_qty.toFixed(3):"")+'"'+lock+'>':'—')+'</td><td><strong class="damaged-short">'+(reusable?damagedShort.toFixed(3):'—')+'</strong></td><td><input class="input reason" type="text" maxlength="255" value="'+esc(d.reason)+'" placeholder="Difference reason"'+lock+'></td></tr>'}).join("");}
function updateRow(row){var item=state.items[Number(row.dataset.index)];if(!item)return;var expected=n(item.expected_return_qty),empty=n(item.empty_collected_qty),damaged=n(item.damaged_collected_qty),af=row.querySelector(".actual-filled"),ae=row.querySelector(".actual-empty"),ad=row.querySelector(".actual-damaged");var filled=Math.max(0,n(af&&af.value)),emptyActual=Math.max(0,n(ae&&ae.value)),damagedActual=Math.max(0,n(ad&&ad.value));row.querySelector(".filled-short").textContent=Math.max(0,r(expected-filled,3)).toFixed(3);var es=row.querySelector(".empty-short"),ds=row.querySelector(".damaged-short");if(es)es.textContent=Math.max(0,r(empty-emptyActual,3)).toFixed(3);if(ds)ds.textContent=Math.max(0,r(damaged-damagedActual,3)).toFixed(3)}
function collect(){return state.items.map(function(item,index){var row=document.querySelector('#returnBody tr[data-index="'+index+'"]');if(!row)return rowData(item);var ae=row.querySelector(".actual-empty"),ad=row.querySelector(".actual-damaged");return{product_id:Number(item.product_id),actual_return_qty:r(row.querySelector(".actual-filled").value,3),actual_empty_return_qty:ae?r(ae.value,3):0,actual_damaged_return_qty:ad?r(ad.value,3):0,reason:(row.querySelector(".reason").value||"").trim()}})}
function renderFinancial(){var f=state.financial||{};document.getElementById("invoiceCount").textContent=String(Number(f.invoice_count||0));document.getElementById("totalSales").textContent=money(f.total_sales);document.getElementById("cash").textContent=money(f.cash);document.getElementById("upi").textContent=money(f.upi);document.getElementById("bank").textContent=money(f.bank);document.getElementById("cheque").textContent=money(f.cheque);document.getElementById("totalReceived").textContent=money(f.total_received);document.getElementById("outstanding").textContent=money(f.outstanding)}
function apply(data){state.actions=(data.allowed_actions||state.actions||[]).map(Number);state.trip=data.trip||{};state.items=data.items||[];state.financial=data.financial||{};renderHeader();renderItems();renderFinancial();var status=Number(state.trip.status||0);document.getElementById("returnButton").hidden=!([2,3].indexOf(status)!==-1&&has(ACTION_RETURN));document.getElementById("closeButton").hidden=!(status===4&&has(ACTION_FINALIZE));document.getElementById("returnRemarks").readOnly=!returnEditable();document.getElementById("deliveryLink").hidden=[4,5,6].indexOf(status)!==-1;if(window.lucide)lucide.createIcons()}
async function submitReturn(){var rows=collect(),bad=false;rows.forEach(function(x,i){var item=state.items[i],fs=Math.max(0,r(n(item.expected_return_qty)-n(x.actual_return_qty),3)),es=Math.max(0,r(n(item.empty_collected_qty)-n(x.actual_empty_return_qty),3)),ds=Math.max(0,r(n(item.damaged_collected_qty)-n(x.actual_damaged_return_qty),3));if((fs>0.0005||es>0.0005||ds>0.0005)&&!x.reason)bad=true});if(bad){showToast("Enter reason for every shortage / difference.",{type:"warning",duration:3});return}try{var x=await App.api("api/truck-return.php",{method:"POST",body:{ref:ref,intent:"return",return_remarks:document.getElementById("returnRemarks").value.trim(),items_json:JSON.stringify(rows)}});apply(x.data);showToast(x.message||"Truck Return submitted.",{type:"success",duration:3})}catch(e){App.showError(e,"Unable to submit Truck Return.")}}
async function closeTrip(){if(!window.confirm("Close this Truck Trip? Closed trips cannot be normally edited."))return;try{var x=await App.api("api/truck-return.php",{method:"POST",body:{ref:ref,intent:"close"}});apply(x.data);showToast("Truck Trip closed.",{type:"success",duration:3})}catch(e){App.showError(e,"Unable to close Truck Trip.")}}
async function load(){if(!ref){showToast("Line Supply reference is required.",{type:"warning",duration:3});document.getElementById("returnButton").hidden=true;document.getElementById("closeButton").hidden=true;return}try{var x=await App.api("api/truck-return.php?ref="+encodeURIComponent(ref));apply(x.data)}catch(e){App.showError(e,"Unable to load Truck Return.")}}
document.getElementById("returnBody").addEventListener("input",function(e){var row=e.target.closest("tr[data-index]");if(row)updateRow(row)});document.getElementById("returnButton").addEventListener("click",submitReturn);document.getElementById("closeButton").addEventListener("click",closeTrip);load();
})(window,document);
</script></section><?php require __DIR__.'/include/footer.php'; ?></main></div></body></html>
